# Información y Programación Financiera, TI, Algoritmos y Ciencia de Datos

Neftalí Valdez

<a href="http://twitter.com/neftalivldz" target="_blank">@neftalivldz</a> | <a href="mailto:nvaldez@tec.mx">nvaldez@tec.mx</a>

In [6]:
import refinitiv.data as rd
import pandas as pd
import numpy as np
import cufflinks as cf  # Cufflinks
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
plt.style.use('seaborn-dark-palette')
import warnings
warnings.filterwarnings('ignore')

In [7]:
rd.open_session()

In [8]:
RICS=['IBM','WMT','MSFT','AAPL','TWTR']
RICS_list=[RIC+"@ticker" for RIC in RICS]

ticker = rd.get_data(RICS_list,'TR.RIC')
ticker

  Instrument           RIC
0        IBM           IBM
1        WMT           WMT
2       MSFT        MSFT.O
3       AAPL        AAPL.O
4       TWTR  THEGQ.PK^D14

# Earnings Per Share

In [9]:
RICS = ['NVDA.O','AAPL.O','IBM','AMZN.O','JPM','GS']
fields = ['TR.EpsSmartEst','TR.EPSMean','TR.EpsPreSurprisePct','TR.EpsPreSurprise','TR.EpsPreSurpriseFlag','TR.EPSMedian','TR.EPSLow','TR.EPSHigh']

eps = rd.get_data(RICS, fields)
eps

,Instrument,Earnings Per Share - SmartEstimate®,Earnings Per Share - Mean,Earnings Per Share - Predicted Surprise PCT,Earnings Per Share - Predicted Surprise,Earnings Per Share - Predicted Surprise Flag,Earnings Per Share - Median,Earnings Per Share - Low,Earnings Per Share - High
0,NVDA.O,10.75966,10.5041,2.433,0.25556,1,10.769,7.4,11.49
1,AAPL.O,6.06681,6.06788,-0.018,-0.00107,0,6.06,6.02,6.17
2,IBM,9.5704,9.56888,0.016,0.00152,0,9.51,9.41,9.87
3,AMZN.O,2.22986,2.20514,1.121,0.02472,0,2.22,1.74,2.57
4,JPM,16.04889,15.97895,0.438,0.06994,0,16.12,14.25,16.79
5,GS,26.07572,26.38605,-1.176,-0.31034,0,26.21,23.58,29.75

# Analyst recommendation

In [10]:
fields = ['TR.AnalystName','TR.RecLabelEstBrokerName','TR.RecEstValue',
          'TR.BrkRecLabel','TR.TPEstValue','TR.EPSLTGEstValue','TR.SingleStockRatingRecommendation1to5T24M',
          'TR.SingleStockRatingRecommendation1to100T24M','TR.RecMean','TR.PriceTargetMean','TR.LTGMean']

analysts = rd.get_data(['CX.N'], fields)
analysts.head(5)

,Instrument,Analyst - Full Name,Broker Name,Standard Rec (1-5) - Broker Estimate,Broker Rec Descr. - Broker Estimate,Target Price - Broker Estimate,LT Growth - Broker Estimate,Analyst Single Stock Rating - Recommendation 1 - 5 Trailing 24m,Analyst Single Stock Rating - Recommendation Trailing 24m,Recommendation - Mean (1-5),Price Target - Mean,Long Term Growth - Mean
0,CX.N,"Ricalde*, Pablo",Permission Denied 36928,2,OVERWEIGHT,9.0,15.6,2,20,2.31818,8.475,
1,CX.N,"Thalhimer, Adam R",Permission Denied 32,3,NEUTRAL,8.2,<NA>,3,53,<NA>,<NA>,
2,CX.N,"Cardona, Andrés",BRADESCO S.A CORRETORA,3,NEUTRAL,7.0,<NA>,1,7,<NA>,<NA>,
3,CX.N,"Goad, Harry F",SANTANDER,3,NEUTRAL,5.7,<NA>,2,18,<NA>,<NA>,
4,CX.N,"Catalan*, Ariana",REDBURN ATLANTIC,3,NEUTRAL,7.3,<NA>,2,20,<NA>,<NA>,

In [11]:
fields = ['TR.AnalystName','TR.RecLabelEstBrokerName','TR.RecEstValue',
          'TR.BrkRecLabel','TR.TPEstValue','TR.EPSLTGEstValue','TR.SingleStockRatingRecommendation1to5T24M',
          'TR.SingleStockRatingRecommendation1to100T24M','TR.RecMean','TR.PriceTargetMean','TR.LTGMean']

analysts = rd.get_data(['NVDA.O'], fields)
analysts.head(5)

,Instrument,Analyst - Full Name,Broker Name,Standard Rec (1-5) - Broker Estimate,Broker Rec Descr. - Broker Estimate,Target Price - Broker Estimate,LT Growth - Broker Estimate,Analyst Single Stock Rating - Recommendation 1 - 5 Trailing 24m,Analyst Single Stock Rating - Recommendation Trailing 24m,Recommendation - Mean (1-5),Price Target - Mean,Long Term Growth - Mean
0,NVDA.O,"Gerra, Tristan",Permission Denied 347360,1,OUTPERFORM,600.0,28.0,5,99,1.78431,621.8814,
1,NVDA.O,"Mosesmann, Hans",Permission Denied 32848,2,OUTPERFORM,630.0,10.0,3,39,<NA>,<NA>,
2,NVDA.O,"Dodonov, Igor",HSBC,2,BUY,560.0,78.7,5,100,<NA>,<NA>,
3,NVDA.O,"Acree, Cody",TRUIST SECURITIES,2,BUY,650.0,20.0,5,99,<NA>,<NA>,
4,NVDA.O,"Pajjuri, Srini R",Permission Denied 392,3,HOLD,668.0,108.42,4,68,<NA>,<NA>,

Total Return

In [12]:
RICs = ['AAPL.O','IBM','MSFT.O','TWTR.K']
start_date = '2019-12-12'
end_date = '2019-12-15'

ts = rd.get_data(RICs,
                   ['TR.PriceClose(SDate=2022-12-12,EDate=2022-12-15,Frq=D).date',
                    'TR.PriceClose(SDate=2022-12-12,EDate=2022-12-15,Frq=D)',
                    'TR.TotalReturn1Mo(SDate=2022-12-12,EDate=2022-12-15,Frq=D)',
                    'TR.TotalReturn(SDate=2022-12-12,EDate=2022-12-15,Frq=D)'
                   ])
ts

   Instrument       Date  Price Close 1 Month Total Return  Total Return
0      AAPL.O 2022-12-12       144.49            -3.480294     -4.685427
1      AAPL.O 2022-12-13       145.47            -2.825651     -1.553585
2      AAPL.O 2022-12-14       143.21            -3.419207      0.678248
3      AAPL.O 2022-12-15        136.5             -9.02426      1.638998
4         IBM 2022-12-12       149.21             4.218761     -5.004671
5         IBM 2022-12-13       150.57             5.168681     -0.471541
6         IBM 2022-12-14       149.86             3.925104      0.911467
7         IBM 2022-12-15       142.36            -1.371761      1.468888
8      MSFT.O 2022-12-12       252.51             2.472714      -3.19182
9      MSFT.O 2022-12-13       256.92             4.262365      0.116768
10     MSFT.O 2022-12-14       257.22             6.786824      1.746465
11     MSFT.O 2022-12-15       249.01             3.198942      2.888925
12     TWTR.K 2022-10-27         53.7                  NaN      0.656045
13     TWTR.K 2022-10-27         53.7                  NaN      0.656045
14     TWTR.K 2022-10-27         53.7                  NaN      0.656045
15     TWTR.K 2022-10-27         53.7                  NaN      0.656045

In [15]:
RICs = ['AAPL.O','IBM','MSFT.O', 'NVDA']

ts= rd.get_data(RICs,
                   ['TR.PriceClose.date','TR.PriceClose','TR.TotalReturn1Mo'],
                   {'SDate':'2023-08-01','EDate':'2023-08-25','Frq':'D'})
ts

   Instrument       Date  Price Close  1 Month Total Return
0      AAPL.O 2023-08-01      195.605              0.842914
1      AAPL.O 2023-08-02       192.58             -0.716606
2      AAPL.O 2023-08-03       191.17             -0.670269
3      AAPL.O 2023-08-04       181.99             -5.440091
4      AAPL.O 2023-08-07       178.85             -6.204112
5      AAPL.O 2023-08-08        179.8             -5.705895
6      AAPL.O 2023-08-09       178.19             -6.550241
7      AAPL.O 2023-08-10       177.97              -5.64127
8      AAPL.O 2023-08-11       177.79             -5.343471
9      AAPL.O 2023-08-14       179.46             -5.762099
10     AAPL.O 2023-08-15       177.45             -6.817588
11     AAPL.O 2023-08-16       176.57             -7.279693
12     AAPL.O 2023-08-17        174.0            -10.183574
13     AAPL.O 2023-08-18       174.49             -9.809763
14     AAPL.O 2023-08-21       175.84              -8.26437
15     AAPL.O 2023-08-22       177.23             -7.539208
16     AAPL.O 2023-08-23       181.12             -5.509797
17     AAPL.O 2023-08-24       176.38              -8.36934
18     AAPL.O 2023-08-25       178.61             -7.627772
19        IBM 2023-08-01       143.33              7.114565
20        IBM 2023-08-02       144.17              7.742321
21        IBM 2023-08-03       144.45              8.064637
22        IBM 2023-08-04       144.24              7.907533
23        IBM 2023-08-07       146.18             10.675348
24        IBM 2023-08-08       145.91             10.470927
25        IBM 2023-08-09       142.49              9.138401
26        IBM 2023-08-10       143.25              9.043532
27        IBM 2023-08-11       143.12              7.696623
28        IBM 2023-08-14       141.91              7.618623
29        IBM 2023-08-15       141.87              7.588289
30        IBM 2023-08-16       140.64              6.655508
31        IBM 2023-08-17       140.66              6.003189
32        IBM 2023-08-18       141.41              5.686627
33        IBM 2023-08-21       142.28              3.596915
34        IBM 2023-08-22       141.49                3.0217
35        IBM 2023-08-23       143.41               4.41969
36        IBM 2023-08-24       143.55              4.072201
37        IBM 2023-08-25       145.35              4.783951
38     MSFT.O 2023-08-01       336.34             -1.233335
39     MSFT.O 2023-08-02        327.5             -3.829212
40     MSFT.O 2023-08-03       326.66              -3.35217
41     MSFT.O 2023-08-04       327.78             -3.020799
42     MSFT.O 2023-08-07       330.11             -2.108416
43     MSFT.O 2023-08-08       326.05             -3.312378
44     MSFT.O 2023-08-09       322.23             -4.445169
45     MSFT.O 2023-08-10       322.93             -2.682096
46     MSFT.O 2023-08-11       321.01             -3.446928
47     MSFT.O 2023-08-14       324.04             -6.140656
48     MSFT.O 2023-08-15       321.86             -6.772101
49     MSFT.O 2023-08-16        320.4              -6.99803
50     MSFT.O 2023-08-17       316.88             -8.150138
51     MSFT.O 2023-08-18       316.48            -11.777329
52     MSFT.O 2023-08-21       321.88             -6.168909
53     MSFT.O 2023-08-22       322.46             -5.999834
54     MSFT.O 2023-08-23        327.0              -4.67638
55     MSFT.O 2023-08-24       319.97              -7.08786
56     MSFT.O 2023-08-25       322.98             -7.782359
57       NVDA        NaT         <NA>                  <NA>

# Análisis de pares
### Basado en el trabajo de  Jirapongse Phuriphanvichai
#### jirapongse-refinitiv
### https://github.com/Refinitiv-API-Samples/Article.EikonAPI.Python.PeerAnalysis

In [16]:
import warnings
import csv
import pandas as pd
import ipywidgets as widgets #IPython widgets 
from ipywidgets import Button, HBox, VBox, Layout, Dropdown, Label
from IPython.display import display, clear_output

Definición de activo a analizar

In [17]:
ric = "NVDA.O"

In [18]:
# Identificar pares

In [19]:
peer_rics = rd.get_data("Peers({})".format(ric), ["TR.PrimaryInstrument"])
peer_rics

   Instrument Primary Instrument RIC
0      AMD.OQ                 AMD.OQ
1     INTC.OQ                INTC.OQ
2     AVGO.OQ                AVGO.OQ
3     QCOM.OQ                QCOM.OQ
4     MRVL.OQ                MRVL.OQ
5     AMBA.OQ                AMBA.OQ
6     CSCO.OQ                CSCO.OQ
7    GOOGL.OQ               GOOGL.OQ
8       HPE.N                  HPE.N
9      ANET.N                 ANET.N
10    LITE.OQ                LITE.OQ
11    AMZN.OQ                AMZN.OQ
12    TSLA.OQ                TSLA.OQ
13     JNPR.N                 JNPR.N
14    BIDU.OQ                BIDU.OQ
15  005930.KS              005930.KS
16     6723.T                 6723.T
17    AAOI.OQ                AAOI.OQ
18     TXN.OQ                 TXN.OQ
19     ADI.OQ                 ADI.OQ
20    SWKS.OQ                SWKS.OQ
21    QRVO.OQ                QRVO.OQ
22      MU.OQ                  MU.OQ
23    NXPI.OQ                NXPI.OQ
24    MCHP.OQ                MCHP.OQ
25      ON.OQ                  ON.OQ
26    AMAT.OQ                AMAT.OQ
27    LRCX.OQ                LRCX.OQ
28     WDC.OQ                 WDC.OQ
29    AAPL.OQ                AAPL.OQ
30     GFS.OQ                 GFS.OQ
31    MPWR.OQ                MPWR.OQ
32    KLAC.OQ                KLAC.OQ
33     STX.OQ                 STX.OQ
34    LSCC.OQ                LSCC.OQ
35    SLAB.OQ                SLAB.OQ
36     WOLF.N                 WOLF.N
37    SMTC.OQ                SMTC.OQ
38    CRDO.OQ                CRDO.OQ
39     TER.OQ                 TER.OQ
40    MTSI.OQ                MTSI.OQ
41    CRUS.OQ                CRUS.OQ
42    SYNA.OQ                SYNA.OQ
43    MSFT.OQ                MSFT.OQ
44     COHR.N                 COHR.N
45    MBLY.OQ                MBLY.OQ
46    ALGM.OQ                ALGM.OQ
47     MXL.OQ                 MXL.OQ
48    NVTS.OQ                NVTS.OQ
49     AIP.OQ                 AIP.OQ

# Información general

In [20]:
fields = ["TR.CommonName",
        "TR.HeadquartersCountry",
        "TR.ExchangeName",
        "TR.TRBCIndustryGroup",
        "TR.GICSSector",
        "TR.TickerSymbol",
        "TR.PriceMoPriceCurrency",
        "TR.CompanyMarketCap(scale=6, curn='USD')",
        "TR.EV(scale=6, curn='USD')"]

In [21]:
df = rd.get_data(ric,fields )

In [22]:
df

,Instrument,Company Common Name,Country of Headquarters,Exchange Name,TRBC Industry Group Name,GICS Sector Name,Ticker Symbol,Price Currency,Company Market Cap,Enterprise Value (Daily Time Series)
0,NVDA.O,NVIDIA Corp,United States of America,NO MARKET (E.G. UNLISTED),Semiconductors & Semiconductor Equipment,Information Technology,NVDA,US Dollar,1136644.6,1130326.6

In [23]:
df1= rd.get_data(peer_rics['Primary Instrument RIC'].tolist(), fields)

In [38]:
df1_alt = df1[df1['TRBC Industry Group Name'] == 'Semiconductors & Semiconductor Equipment'].iloc[:10]
df1_alt

,Instrument,Company Common Name,Country of Headquarters,Exchange Name,TRBC Industry Group Name,GICS Sector Name,Ticker Symbol,Price Currency,Company Market Cap,Enterprise Value (Daily Time Series)
0,AMD.OQ,Advanced Micro Devices Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,AMD,US Dollar,165202.398605,161384.398605
1,INTC.OQ,Intel Corp,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,INTC,US Dollar,139251.0,167494.0
2,AVGO.OQ,Broadcom Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,AVGO,US Dollar,351533.681687,375554.681687
3,QCOM.OQ,Qualcomm Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,QCOM,US Dollar,123117.12,129930.12
4,MRVL.OQ,Marvell Technology Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,MRVL,US Dollar,46010.0,49739.7
5,AMBA.OQ,Ambarella Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,AMBA,US Dollar,2775.338785,2547.950785
16,6723.T,Renesas Electronics Corp,Japan,TOKYO STOCK EXCHANGE,Semiconductors & Semiconductor Equipment,Information Technology,6723,Japanese Yen,31994.213593,33621.91747
18,TXN.OQ,Texas Instruments Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,TXN,US Dollar,152365.829334,154032.829334
19,ADI.OQ,Analog Devices Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,ADI,US Dollar,88779.614401,94612.728401
20,SWKS.OQ,Skyworks Solutions Inc,United States of America,NASDAQ/NGS (GLOBAL SELECT MARKET),Semiconductors & Semiconductor Equipment,Information Technology,SWKS,US Dollar,16798.383374,17553.483374

# Razones financieras

In [25]:
fields_ratios = ["TR.CommonName",
    "TR.PE()",
    "TR.PtoEPSMeanEst(Period=FY1)",
    "TR.PriceToSalesPerShare",
    "TR.EVToEBITDA",
    "TR.PricetoCFPerShare",
    "TR.PriceToBVPerShare",
    "TR.DividendYield"]

In [39]:
df_a = rd.get_data(ric, fields_ratios)
df_a

,Instrument,Company Common Name,P/E (Daily Time Series Ratio),Price / EPS (Mean Estimate),Price To Sales Per Share (Daily Time Series Ratio),Enterprise Value To EBITDA (Daily Time Series Ratio),Price To Cash Flow Per Share (Daily Time Series Ratio),Price To Book Value Per Share (Daily Time Series Ratio),Dividend yield
0,NVDA.O,NVIDIA Corp,111.164524,43.80956,34.779982,86.172646,95.52438,41.331028,0.033925

In [41]:
df2_a = rd.get_data(df1_alt['Instrument'].tolist(), fields_ratios)
df2_a

,Instrument,Company Common Name,P/E (Daily Time Series Ratio),Price / EPS (Mean Estimate),Price To Sales Per Share (Daily Time Series Ratio),Enterprise Value To EBITDA (Daily Time Series Ratio),Price To Cash Flow Per Share (Daily Time Series Ratio),Price To Book Value Per Share (Daily Time Series Ratio),Dividend yield
0,AMD.OQ,Advanced Micro Devices Inc,<NA>,37.085531,7.551764,42.391489,68.920483,2.993171,<NA>
1,INTC.OQ,Intel Corp,<NA>,53.515097,2.576623,17.584672,14.27337,1.378491,1.534213
2,AVGO.OQ,Broadcom Inc,26.652482,20.31117,10.031781,18.515736,20.036118,16.024605,2.153407
3,QCOM.OQ,Qualcomm Inc,14.414622,13.281837,3.190885,10.662245,14.224971,5.950982,2.949037
4,MRVL.OQ,Marvell Technology Inc,<NA>,34.814863,8.189164,39.223799,42.468156,2.989701,0.418921
5,AMBA.OQ,Ambarella Inc,<NA>,NaN,8.968821,<NA>,85.242914,4.577025,<NA>
6,6723.T,Renesas Electronics Corp,12.679546,11.116947,3.098861,8.410434,9.72307,2.22395,0.0
7,TXN.OQ,Texas Instruments Inc,20.141921,22.844595,8.095523,15.417158,20.682208,9.559064,2.99535
8,ADI.OQ,Analog Devices Inc,24.207377,17.594433,6.916039,13.783396,18.5744,2.472712,1.98054
9,SWKS.OQ,Skyworks Solutions Inc,16.240856,12.556578,3.386429,8.877501,9.725789,2.854436,2.609613

In [42]:
df_concat = pd.concat((df_a, df2_a))
df = df_a.set_index('Instrument')
df.loc["Peer Median"] = df_concat.median()
df.loc["Peer Average"] = df_concat.mean()
df.loc["Peer Median", "Company Common Name"] = ""
df.loc["Peer Average", "Company Common Name"] = ""

In [44]:
df_concat.median()

P/E (Daily Time Series Ratio)                              20.141921
Price / EPS (Mean Estimate)                                21.577883
Price To Sales Per Share (Daily Time Series Ratio)          7.551764
Enterprise Value To EBITDA (Daily Time Series Ratio)       16.500915
Price To Cash Flow Per Share (Daily Time Series Ratio)     20.036118
Price To Book Value Per Share (Daily Time Series Ratio)     2.993171
Dividend yield                                              1.980540
dtype: float64

In [39]:
df_concat.median()

P/E (Daily Time Series Ratio)                             28.42
Price / EPS (Mean Estimate)                               23.34
Price To Sales Per Share (Daily Time Series Ratio)         3.99
Enterprise Value To EBITDA (Daily Time Series Ratio)      16.84
Price To Cash Flow Per Share (Daily Time Series Ratio)    20.10
Price To Book Value Per Share (Daily Time Series Ratio)    5.85
Dividend yield                                             2.05
dtype: float64

In [40]:
df_concat.mean()

P/E (Daily Time Series Ratio)                             50.89
Price To Sales Per Share (Daily Time Series Ratio)         5.87
Enterprise Value To EBITDA (Daily Time Series Ratio)      28.83
Price To Cash Flow Per Share (Daily Time Series Ratio)    24.71
Price To Book Value Per Share (Daily Time Series Ratio)   12.93
Dividend yield                                             2.10
dtype: float64

In [45]:
df

,Company Common Name,P/E (Daily Time Series Ratio),Price / EPS (Mean Estimate),Price To Sales Per Share (Daily Time Series Ratio),Enterprise Value To EBITDA (Daily Time Series Ratio),Price To Cash Flow Per Share (Daily Time Series Ratio),Price To Book Value Per Share (Daily Time Series Ratio),Dividend yield
Instrument,,,,,,,,
NVDA.O,NVIDIA Corp,111.164524,43.80956,34.779982,86.172646,95.52438,41.331028,0.033925
Peer Median,,20.141921,21.577883,7.551764,16.500915,20.036118,2.993171,1.98054
Peer Average,,32.214476,NaN,8.798716,26.103908,36.308714,8.395924,1.630556

# Income Statement

In [47]:
fields_IS = ["TR.CommonName",
            "TR.ReturnonAvgTotEqtyPctNetIncomeBeforeExtraItemsTTM",
            "TR.ROAPercentTrailing12M",
            "TR.GrossProfit(Period=FY0)",
            "TR.TotalRevenue(Period=FY0)",
            "TR.OperatingProfit(Period=FY0)",
            "TR.OperatingProfitMarginPct5YrAvg",
            "TR.PretaxMarginPercent(period=FY0)",
            "TR.EBITDATotEqtyPctTTM"]

In [51]:
ric = "GOOGL.OQ"
fields = fields_IS 
df_a = rd.get_data(ric, fields)
peers = rd.get_data("Peers({})".format(ric), ["TR.PrimaryInstrument"])
df2_a = rd.get_data(peers['Primary Instrument RIC'].tolist(), fields)
df_concat = pd.concat((df_a, df2_a))
df_concat2 = df_concat.reset_index(drop=True)

In [52]:
df_concat2

,Instrument,Company Common Name,"ROE Total Equity %, TTM","ROA Total Assets Percent, Trailing 12 Months",Gross Profit,Total Revenue,Operating Profit,"Oper Profit Margin, %, 5 Yr Avg","Pretax Margin, Percent","EBITDA/Tot Eqty, %, TTM"
0,GOOGL.OQ,Alphabet Inc,23.328613,16.513304,156633000000,282836000000,74842000000.0,25.109232,25.21885,35.213947
1,META.OQ,Meta Platforms Inc,18.518091,12.779341,92855000000,116609000000,28944000000.0,35.179783,24.71422,30.487298
2,AMZN.OQ,Amazon.com Inc,8.71455,2.91307,225152000000,513983000000,12248000000.0,4.618968,-1.1549,42.5181
3,SNAP.N,Snap Inc,-45.520523,-16.454309,2807090000,4601847000,-1395306000.0,-37.46999,-30.43771,-38.455439
4,EBAY.OQ,eBay Inc,25.535154,6.776238,7115000000,9795000000,2350000000.0,24.722492,-16.34507,56.96889
5,NFLX.OQ,Netflix Inc,18.503687,7.980536,12447265000,31615550000,5632831000.0,16.867388,16.64981,97.599736
6,MSFT.OQ,Microsoft Corp,38.823924,18.630152,146052000000,211915000000,88493000000.0,39.832918,42.14473,55.560474
7,BABA.N,Alibaba Group Holding Ltd,8.427219,4.591337,320125000000,868687000000,100707000000.0,14.2285,10.26664,21.199813
8,AAPL.OQ,Apple Inc,160.093258,28.229813,170782000000,394328000000,119437000000.0,27.52461,30.20404,209.420431
9,CRM.N,Salesforce Inc,0.65183,0.406297,22992000000,31352000000,539000000.0,2.121926,2.10513,12.202463
10,BIDU.OQ,Baidu Inc,6.185432,3.777176,67541000000,123675000000,12911000000.0,8.639093,8.17627,10.610381
11,ZM.OQ,Zoom Video Communications Inc,0.088149,0.066659,3292509000,4392960000,245429000.0,16.431104,5.67444,3.611067
12,CRTO.OQ,Criteo SA,0.697566,0.426484,795200000,2017003000,24278000.0,5.2569,2.08532,16.444258
13,VZ.N,Verizon Communications Inc,23.215182,5.734153,77702000000,136835000000,30901000000.0,21.101605,20.66065,52.366052
14,T.N,AT&T Inc,-8.0055,-1.810786,69893000000,120741000000,-4587000000.0,11.277872,-2.56251,38.79007
15,YNDX.OQ,Yandex NV,23.828605,12.872401,288480000000,521699000000,60591999999.999901,11.138872,13.4846,26.355475
16,035420.KS,Naver Corp,3.247191,2.042606,<NA>,8220078708810,1229080027540.0,20.375987,13.18378,8.611113
17,TWTR.N^J22,Twitter Inc,-1.638028,-0.773524,3279972000,5077482000,-408039000.0,2.261808,-8.09679,4.857462
18,PINS.N,Pinterest Inc,-9.991507,-8.446005,2123977000,2802574000,-101677000.0,-15.39889,-3.06661,-6.575137
19,UBER.N,Uber Technologies Inc,-4.880914,-1.471989,9805000000,31877000000,-2000000000.0,-22.013253,-29.56991,11.928222
20,LYFT.OQ,Lyft Inc,-193.787833,-28.515368,1215553000,4095135000,-1594630000.0,-52.453115,-38.54913,-139.102569
21,ABNB.OQ,Airbnb Inc,44.641798,11.429144,5859000000,8399000000,1802000000.0,-8.608302,23.68139,38.788939
22,DASH.N,DoorDash Inc,-18.339852,-13.026781,2995000000,6583000000,-1124000000.0,<NA>,-21.25171,-4.78053
23,BKNG.OQ,Booking Holdings Inc,267.126161,17.46097,<NA>,17090000000,5102000000.0,26.865,22.95494,376.74558
24,EXPE.OQ,Expedia Group Inc,49.005179,3.562079,10010000000,11667000000,1140000000.0,0.793781,4.6113,111.420005
25,SPOT.N,Spotify Technology SA,-44.225029,-13.102041,2926000000,11727000000,-659000000.0,-2.360889,-3.15511,-24.064294
26,SHOP.N,Shopify Inc,-25.031977,-19.804798,2754119000,5599864000,-822299000.0,-4.410733,-64.69529,-11.367871
27,IAC.OQ,IAC Inc,4.308174,2.299083,3338393000,5235280000,-415472000.0,-5.86678,-29.1529,2.486442
28,ZG.OQ,Zillow Group Inc,-3.889435,-2.656518,1600000000,1958000000,-93000000.0,-4.875084,-4.34116,-1.070687
29,TTD.OQ,Trade Desk Inc,6.715809,3.225078,1296672000,1577795000,113654000.0,12.681465,8.07266,11.242558
30,ORCL.N,Oracle Corp,<NA>,6.979617,36390000000,49954000000,13093000000.0,31.527049,18.26881,<NA>
31,ROKU.OQ,Roku Inc,-24.791004,-15.597513,1441122000,3126534000,-530888000.0,-4.133726,-15.74533,-23.88347
32,MTCH.OQ,Match Group Inc,<NA>,11.061404,2231180000,3188843000,518505000.0,23.447063,11.83787,<NA>
33,PTON.OQ,Peloton Interactive Inc,-279.840098,-61.23185,698300000,3582100000,-2734000000.0,-30.171246,-78.39256,-155.166052
34,BMBL.OQ,Bumble Inc,-5.260843,-3.373165,654132000,903503000,-102844000.0,<NA>,-12.2543,9.054683
35,UPWK.OQ,Upwork Inc,-10.17674,-2.780914,457916000,618318000,-92624000.0,-9.747498,-14.45033,-24.963398
36,9618.HK,JD.Com Inc,10.322334,3.853028,147073000000,1046236000000,14196000000.0,0.969329,1.32542,16.705664
37,DIS.N,Walt Disney Co,2.369155,1.446585,28321000000,82722000000,6529000000.0,10.738633,6.38887,13.313345
38,0700.HK,Tencent Holdings Ltd,26.171284,13.290061,238887000000,554552000000,235706000000.0,39.703426,37.90898,25.354141
39,WBD.OQ,Warner Bros Discovery Inc,-13.875148,-4.905892,13426000000,33817000000,-7370000000.0,2.509697,-26.49555,50.500336
40,NVDA.OQ,NVIDIA Corp,18.855232,10.69007,16053000000,26974000000,4224000000.0,27.304527,15.50011,27.006294
41,ADBE.OQ,Adobe Inc,33.681435,17.923344,15441000000,17606000000,6098000000.0,33.471845,34.12473,49.002533
42,W.N,Wayfair Inc,<NA>,-27.673797,3383000000,12218000000,-1288000000.0,-4.331876,-10.79555,<NA>
43,EA.OQ,Electronic Arts Inc,11.926544,6.797336,5646000000,7426000000,1332000000.0,19.480562,17.85618,28.006678
44,SNOW.N,Snowflake Inc.,-15.944138,-11.856631,1348119000,2065659000,-880303000.0,<NA>,-39.50279,-15.792894
45,ANGI.OQ,Angi Inc,-9.48231,-5.11142,1453464000,1891524000,-126305000.0,-1.241688,-7.67815,3.627312
46,TRIP.OQ,Tripadvisor Inc,-3.2974,-0.97269,1376000000,1492000000,101000000.0,0.097197,4.49062,23.842739
47,TRVG.OQ,Trivago NV,-6.789287,-5.385695,522313000,535004000,-120262000.0,-11.862642,-22.47591,12.10088
48,DV.N,DoubleVerify Holdings Inc,6.08502,5.189048,374552000,452418000,59024000.0,<NA>,13.12238,12.552255
49,FVRR.N,Fiverr International Ltd,-6.186079,-1.772515,271418000,337366000,-74534000.0,-20.146974,-21.01872,-7.063558
50,PARA.OQ,Paramount Global,-7.017623,-1.999608,10309000000,30154000000,2222000000.0,15.73686,4.19845,0.823749

In [53]:
df

,Company Common Name,P/E (Daily Time Series Ratio),Price / EPS (Mean Estimate),Price To Sales Per Share (Daily Time Series Ratio),Enterprise Value To EBITDA (Daily Time Series Ratio),Price To Cash Flow Per Share (Daily Time Series Ratio),Price To Book Value Per Share (Daily Time Series Ratio),Dividend yield
Instrument,,,,,,,,
NVDA.O,NVIDIA Corp,111.164524,43.80956,34.779982,86.172646,95.52438,41.331028,0.033925
Peer Median,,20.141921,21.577883,7.551764,16.500915,20.036118,2.993171,1.98054
Peer Average,,32.214476,NaN,8.798716,26.103908,36.308714,8.395924,1.630556

In [54]:
df_concat

,Instrument,Company Common Name,"ROE Total Equity %, TTM","ROA Total Assets Percent, Trailing 12 Months",Gross Profit,Total Revenue,Operating Profit,"Oper Profit Margin, %, 5 Yr Avg","Pretax Margin, Percent","EBITDA/Tot Eqty, %, TTM"
0,GOOGL.OQ,Alphabet Inc,23.328613,16.513304,156633000000,282836000000,74842000000.0,25.109232,25.21885,35.213947
0,META.OQ,Meta Platforms Inc,18.518091,12.779341,92855000000,116609000000,28944000000.0,35.179783,24.71422,30.487298
1,AMZN.OQ,Amazon.com Inc,8.71455,2.91307,225152000000,513983000000,12248000000.0,4.618968,-1.1549,42.5181
2,SNAP.N,Snap Inc,-45.520523,-16.454309,2807090000,4601847000,-1395306000.0,-37.46999,-30.43771,-38.455439
3,EBAY.OQ,eBay Inc,25.535154,6.776238,7115000000,9795000000,2350000000.0,24.722492,-16.34507,56.96889
4,NFLX.OQ,Netflix Inc,18.503687,7.980536,12447265000,31615550000,5632831000.0,16.867388,16.64981,97.599736
5,MSFT.OQ,Microsoft Corp,38.823924,18.630152,146052000000,211915000000,88493000000.0,39.832918,42.14473,55.560474
6,BABA.N,Alibaba Group Holding Ltd,8.427219,4.591337,320125000000,868687000000,100707000000.0,14.2285,10.26664,21.199813
7,AAPL.OQ,Apple Inc,160.093258,28.229813,170782000000,394328000000,119437000000.0,27.52461,30.20404,209.420431
8,CRM.N,Salesforce Inc,0.65183,0.406297,22992000000,31352000000,539000000.0,2.121926,2.10513,12.202463
9,BIDU.OQ,Baidu Inc,6.185432,3.777176,67541000000,123675000000,12911000000.0,8.639093,8.17627,10.610381
10,ZM.OQ,Zoom Video Communications Inc,0.088149,0.066659,3292509000,4392960000,245429000.0,16.431104,5.67444,3.611067
11,CRTO.OQ,Criteo SA,0.697566,0.426484,795200000,2017003000,24278000.0,5.2569,2.08532,16.444258
12,VZ.N,Verizon Communications Inc,23.215182,5.734153,77702000000,136835000000,30901000000.0,21.101605,20.66065,52.366052
13,T.N,AT&T Inc,-8.0055,-1.810786,69893000000,120741000000,-4587000000.0,11.277872,-2.56251,38.79007
14,YNDX.OQ,Yandex NV,23.828605,12.872401,288480000000,521699000000,60591999999.999901,11.138872,13.4846,26.355475
15,035420.KS,Naver Corp,3.247191,2.042606,<NA>,8220078708810,1229080027540.0,20.375987,13.18378,8.611113
16,TWTR.N^J22,Twitter Inc,-1.638028,-0.773524,3279972000,5077482000,-408039000.0,2.261808,-8.09679,4.857462
17,PINS.N,Pinterest Inc,-9.991507,-8.446005,2123977000,2802574000,-101677000.0,-15.39889,-3.06661,-6.575137
18,UBER.N,Uber Technologies Inc,-4.880914,-1.471989,9805000000,31877000000,-2000000000.0,-22.013253,-29.56991,11.928222
19,LYFT.OQ,Lyft Inc,-193.787833,-28.515368,1215553000,4095135000,-1594630000.0,-52.453115,-38.54913,-139.102569
20,ABNB.OQ,Airbnb Inc,44.641798,11.429144,5859000000,8399000000,1802000000.0,-8.608302,23.68139,38.788939
21,DASH.N,DoorDash Inc,-18.339852,-13.026781,2995000000,6583000000,-1124000000.0,<NA>,-21.25171,-4.78053
22,BKNG.OQ,Booking Holdings Inc,267.126161,17.46097,<NA>,17090000000,5102000000.0,26.865,22.95494,376.74558
23,EXPE.OQ,Expedia Group Inc,49.005179,3.562079,10010000000,11667000000,1140000000.0,0.793781,4.6113,111.420005
24,SPOT.N,Spotify Technology SA,-44.225029,-13.102041,2926000000,11727000000,-659000000.0,-2.360889,-3.15511,-24.064294
25,SHOP.N,Shopify Inc,-25.031977,-19.804798,2754119000,5599864000,-822299000.0,-4.410733,-64.69529,-11.367871
26,IAC.OQ,IAC Inc,4.308174,2.299083,3338393000,5235280000,-415472000.0,-5.86678,-29.1529,2.486442
27,ZG.OQ,Zillow Group Inc,-3.889435,-2.656518,1600000000,1958000000,-93000000.0,-4.875084,-4.34116,-1.070687
28,TTD.OQ,Trade Desk Inc,6.715809,3.225078,1296672000,1577795000,113654000.0,12.681465,8.07266,11.242558
29,ORCL.N,Oracle Corp,<NA>,6.979617,36390000000,49954000000,13093000000.0,31.527049,18.26881,<NA>
30,ROKU.OQ,Roku Inc,-24.791004,-15.597513,1441122000,3126534000,-530888000.0,-4.133726,-15.74533,-23.88347
31,MTCH.OQ,Match Group Inc,<NA>,11.061404,2231180000,3188843000,518505000.0,23.447063,11.83787,<NA>
32,PTON.OQ,Peloton Interactive Inc,-279.840098,-61.23185,698300000,3582100000,-2734000000.0,-30.171246,-78.39256,-155.166052
33,BMBL.OQ,Bumble Inc,-5.260843,-3.373165,654132000,903503000,-102844000.0,<NA>,-12.2543,9.054683
34,UPWK.OQ,Upwork Inc,-10.17674,-2.780914,457916000,618318000,-92624000.0,-9.747498,-14.45033,-24.963398
35,9618.HK,JD.Com Inc,10.322334,3.853028,147073000000,1046236000000,14196000000.0,0.969329,1.32542,16.705664
36,DIS.N,Walt Disney Co,2.369155,1.446585,28321000000,82722000000,6529000000.0,10.738633,6.38887,13.313345
37,0700.HK,Tencent Holdings Ltd,26.171284,13.290061,238887000000,554552000000,235706000000.0,39.703426,37.90898,25.354141
38,WBD.OQ,Warner Bros Discovery Inc,-13.875148,-4.905892,13426000000,33817000000,-7370000000.0,2.509697,-26.49555,50.500336
39,NVDA.OQ,NVIDIA Corp,18.855232,10.69007,16053000000,26974000000,4224000000.0,27.304527,15.50011,27.006294
40,ADBE.OQ,Adobe Inc,33.681435,17.923344,15441000000,17606000000,6098000000.0,33.471845,34.12473,49.002533
41,W.N,Wayfair Inc,<NA>,-27.673797,3383000000,12218000000,-1288000000.0,-4.331876,-10.79555,<NA>
42,EA.OQ,Electronic Arts Inc,11.926544,6.797336,5646000000,7426000000,1332000000.0,19.480562,17.85618,28.006678
43,SNOW.N,Snowflake Inc.,-15.944138,-11.856631,1348119000,2065659000,-880303000.0,<NA>,-39.50279,-15.792894
44,ANGI.OQ,Angi Inc,-9.48231,-5.11142,1453464000,1891524000,-126305000.0,-1.241688,-7.67815,3.627312
45,TRIP.OQ,Tripadvisor Inc,-3.2974,-0.97269,1376000000,1492000000,101000000.0,0.097197,4.49062,23.842739
46,TRVG.OQ,Trivago NV,-6.789287,-5.385695,522313000,535004000,-120262000.0,-11.862642,-22.47591,12.10088
47,DV.N,DoubleVerify Holdings Inc,6.08502,5.189048,374552000,452418000,59024000.0,<NA>,13.12238,12.552255
48,FVRR.N,Fiverr International Ltd,-6.186079,-1.772515,271418000,337366000,-74534000.0,-20.146974,-21.01872,-7.063558
49,PARA.OQ,Paramount Global,-7.017623,-1.999608,10309000000,30154000000,2222000000.0,15.73686,4.19845,0.823749

In [55]:
def gt_comparison(ric, fields):
    df_a = rd.get_data(ric, fields)
    peers = rd.get_data("Peers({})".format(ric), ["TR.PrimaryInstrument"])
    df2_a = rd.get_data(peers['Primary Instrument RIC'].tolist(), fields)
    df_concat = pd.concat((df_a, df2_a))
    dfs = df_a.set_index('Instrument')
    dfs.loc["Peer Median"] = df_concat.median()
    dfs.loc["Peer Average"] = df_concat.mean()
    dfs.loc["Peer Median", "Company Common Name"] = ""
    dfs.loc["Peer Average", "Company Common Name"] = ""
    return dfs, df_concat

In [59]:
df_ms, df_ms_peers = gt_comparison("AMZN.O", fields_IS)

In [60]:
df_ms

,Company Common Name,"ROE Total Equity %, TTM","ROA Total Assets Percent, Trailing 12 Months",Gross Profit,Total Revenue,Operating Profit,"Oper Profit Margin, %, 5 Yr Avg","Pretax Margin, Percent","EBITDA/Tot Eqty, %, TTM"
Instrument,,,,,,,,,
AMZN.O,Amazon.com Inc,8.71455,2.91307,225152000000.0,513983000000.0,12248000000.0,4.618968,-1.1549,42.5181
Peer Median,,8.427219,2.606077,6250000000.0,12726000000.0,539000000.0,2.360329,1.9574,25.880626
Peer Average,,-26.150041,-1.612839,35818796700.0,101341756000.0,10133828980.392157,2.153174,-3.149819,51.254712

In [61]:
df_ms_peers

,Instrument,Company Common Name,"ROE Total Equity %, TTM","ROA Total Assets Percent, Trailing 12 Months",Gross Profit,Total Revenue,Operating Profit,"Oper Profit Margin, %, 5 Yr Avg","Pretax Margin, Percent","EBITDA/Tot Eqty, %, TTM"
0,AMZN.O,Amazon.com Inc,8.71455,2.91307,225152000000,513983000000,12248000000,4.618968,-1.1549,42.5181
0,ETSY.OQ,ETSY Inc,-1218.374317,-23.105476,1821519000,2566111000,-658560000,4.698205,-25.79694,799.750683
1,W.N,Wayfair Inc,<NA>,-27.673797,3383000000,12218000000,-1288000000,-4.331876,-10.79555,<NA>
2,TGT.N,Target Corp,29.87335,6.383663,26891000000,109120000000,3848000000,6.039978,3.13233,66.212027
3,COST.OQ,Costco Wholesale Corp,27.563396,9.203393,27572000000,226954000000,7793000000,3.298138,3.45444,45.079934
4,BBY.N,Best Buy Co Inc,47.553957,8.83129,9912000000,46298000000,1795000000,4.802491,3.86194,97.553957
5,GRPN.OQ,Groupon Inc,-289.927113,-26.589316,522824000,599085000,-167815000,-4.944964,-32.04387,-47.391451
6,M.N,Macy's Inc,28.11493,6.187943,9999000000,25305000000,1660000000,1.381884,5.99881,63.319012
7,JWN.N,Nordstrom Inc,3.508772,0.222198,5511000000,15530000000,465000000,2.114115,2.16999,194.385965
8,KSS.N,Kohls Corp,-0.464775,-0.126823,6641000000,18098000000,246000000,4.12962,-0.32048,25.880626
9,ASOS.L,ASOS PLC,-25.585312,-8.297366,1717500000,3936500000,-9800000,2.880459,-0.81036,10.625238
10,META.OQ,Meta Platforms Inc,18.518091,12.779341,92855000000,116609000000,28944000000,35.179783,24.71422,30.487298
11,GOOGL.OQ,Alphabet Inc,23.328613,16.513304,156633000000,282836000000,74842000000,25.109232,25.21885,35.213947
12,SNAP.N,Snap Inc,-45.520523,-16.454309,2807090000,4601847000,-1395306000,-37.46999,-30.43771,-38.455439
13,PINS.N,Pinterest Inc,-9.991507,-8.446005,2123977000,2802574000,-101677000,-15.39889,-3.06661,-6.575137
14,UBER.N,Uber Technologies Inc,-4.880914,-1.471989,9805000000,31877000000,-2000000000,-22.013253,-29.56991,11.928222
15,EBAY.OQ,eBay Inc,25.535154,6.776238,7115000000,9795000000,2350000000,24.722492,-16.34507,56.96889
16,ABNB.OQ,Airbnb Inc,44.641798,11.429144,5859000000,8399000000,1802000000,-8.608302,23.68139,38.788939
17,BKNG.OQ,Booking Holdings Inc,267.126161,17.46097,<NA>,17090000000,5102000000,26.865,22.95494,376.74558
18,DASH.N,DoorDash Inc,-18.339852,-13.026781,2995000000,6583000000,-1124000000,<NA>,-21.25171,-4.78053
19,LYFT.OQ,Lyft Inc,-193.787833,-28.515368,1215553000,4095135000,-1594630000,-52.453115,-38.54913,-139.102569
20,EXPE.OQ,Expedia Group Inc,49.005179,3.562079,10010000000,11667000000,1140000000,0.793781,4.6113,111.420005
21,MSFT.OQ,Microsoft Corp,38.823924,18.630152,146052000000,211915000000,88493000000,39.832918,42.14473,55.560474
22,NFLX.OQ,Netflix Inc,18.503687,7.980536,12447265000,31615550000,5632831000,16.867388,16.64981,97.599736
23,CHWY.N,Chewy Inc,31.052716,2.14841,2830905000,10098939000,55753000,-1.817676,0.5137,91.406701
24,SHOP.N,Shopify Inc,-25.031977,-19.804798,2754119000,5599864000,-822299000,-4.410733,-64.69529,-11.367871
25,IAC.OQ,IAC Inc,4.308174,2.299083,3338393000,5235280000,-415472000,-5.86678,-29.1529,2.486442
26,AAPL.OQ,Apple Inc,160.093258,28.229813,170782000000,394328000000,119437000000,27.52461,30.20404,209.420431
27,ZG.OQ,Zillow Group Inc,-3.889435,-2.656518,1600000000,1958000000,-93000000,-4.875084,-4.34116,-1.070687
28,BABA.N,Alibaba Group Holding Ltd,8.427219,4.591337,320125000000,868687000000,100707000000,14.2285,10.26664,21.199813
29,PTON.OQ,Peloton Interactive Inc,-279.840098,-61.23185,698300000,3582100000,-2734000000,-30.171246,-78.39256,-155.166052
30,WMT.N,Walmart Inc,17.872395,5.570553,147568000000,611289000000,20428000000,3.416532,2.78363,46.368178
31,CRM.N,Salesforce Inc,0.65183,0.406297,22992000000,31352000000,539000000,2.121926,2.10513,12.202463
32,ROKU.OQ,Roku Inc,-24.791004,-15.597513,1441122000,3126534000,-530888000,-4.133726,-15.74533,-23.88347
33,KR.N,Kroger Co,25.024611,5.126707,32808000000,148258000000,4126000000,2.598733,1.9574,72.051585
34,DG.N,Dollar General Corp,39.972043,8.37809,11820098000,37844863000,3328302000,9.122587,8.23524,68.542773
35,FTCH.N,Farfetch Ltd,<NA>,<NA>,1023175000,2316680000,-847160000,-32.348982,14.73367,<NA>
36,ANGI.OQ,Angi Inc,-9.48231,-5.11142,1453464000,1891524000,-126305000,-1.241688,-7.67815,3.627312
37,TRIP.OQ,Tripadvisor Inc,-3.2974,-0.97269,1376000000,1492000000,101000000,0.097197,4.49062,23.842739
38,TRVG.OQ,Trivago NV,-6.789287,-5.385695,522313000,535004000,-120262000,-11.862642,-22.47591,12.10088
39,FVRR.N,Fiverr International Ltd,-6.186079,-1.772515,271418000,337366000,-74534000,-20.146974,-21.01872,-7.063558
40,9618.HK,JD.Com Inc,10.322334,3.853028,147073000000,1046236000000,14196000000,0.969329,1.32542,16.705664
41,ORCL.N,Oracle Corp,<NA>,6.979617,36390000000,49954000000,13093000000,31.527049,18.26881,<NA>
42,DLTR.OQ,Dollar Tree Inc,16.078221,6.059687,8935400000,28331700000,2236300000,4.943509,7.44961,31.501879
43,NVDA.OQ,NVIDIA Corp,18.855232,10.69007,16053000000,26974000000,4224000000,27.304527,15.50011,27.006294
44,BIDU.OQ,Baidu Inc,6.185432,3.777176,67541000000,123675000000,12911000000,8.639093,8.17627,10.610381
45,INTU.OQ,Intuit Inc,12.959801,7.79664,10320000000,12726000000,2571000000,24.881555,19.97485,22.388794
46,SPOT.N,Spotify Technology SA,-44.225029,-13.102041,2926000000,11727000000,-659000000,-2.360889,-3.15511,-24.064294
47,CVNA.N,Carvana Co,<NA>,-25.502697,1246000000,13604000000,-2893000000,-11.242399,-21.2658,<NA>
48,EA.OQ,Electronic Arts Inc,11.926544,6.797336,5646000000,7426000000,1332000000,19.480562,17.85618,28.006678
49,TTWO.OQ,Take-Two Interactive Software Inc,-13.18855,-7.374167,2364400000,5349900000,-1165200000,3.167769,-25.01168,8.384895

In [53]:
def gt_comparison(ric, fields):
    df_a = rd.get_data(ric, fields)
    peers = rd.get_data("Peers({})".format(ric), ["TR.PrimaryInstrument"])
    df2_a = rd.get_data(peers['Primary Instrument RIC'].tolist(), fields)
    df_concat = pd.concat((df_a, df2_a)).reset_index(drop=True)
    dfs = df_a.set_index('Instrument')
    dfs.loc["Peer Median"] = df_concat.median()
    dfs.loc["Peer Average"] = df_concat.mean()
    dfs.loc["Peer Median", "Company Common Name"] = ""
    dfs.loc["Peer Average", "Company Common Name"] = ""
    return dfs, df_concat

In [54]:
df_ms, df_ms_peers = gt_comparison("MSFT.OQ", fields_IS)
df_ms_peers

,Instrument,Company Common Name,"ROE Total Equity %, TTM","ROA Total Assets Percent, Trailing 12 Months",Gross Profit,Total Revenue,Operating Profit,"Oper Profit Margin, %, 5 Yr Avg","Pretax Margin, Percent","EBITDA/Tot Eqty, %, TTM"
0,MSFT.OQ,Microsoft Corp,38.82,18.63,146052000000,211915000000,88493000000,39.83,42.14,55.56
1,CRM.N,Salesforce Inc,0.65,0.41,22992000000,31352000000,539000000,2.12,2.11,12.20
2,ORCL.N,Oracle Corp,<NA>,6.98,36390000000,49954000000,13093000000,31.53,18.27,<NA>
3,ADBE.OQ,Adobe Inc,33.68,17.92,15441000000,17606000000,6098000000,33.47,34.12,49.00
4,AMZN.OQ,Amazon.com Inc,8.71,2.91,225152000000,513983000000,12248000000,4.62,-1.15,42.52
5,META.OQ,Meta Platforms Inc,18.52,12.78,92855000000,116609000000,28944000000,35.18,24.71,30.49
6,IBM.N,International Business Machines Corp,9.67,1.55,32688000000,60530000000,1156000000,8.74,1.91,62.61
7,AAPL.OQ,Apple Inc,160.09,28.23,170782000000,394328000000,119437000000,27.52,30.20,209.42
8,OKTA.OQ,Okta Inc,-12.56,-7.70,1312000000,1858000000,-812000000,-42.29,-43.11,-10.41
9,VMW.N,VMware Inc,178.02,4.47,10868000000,13350000000,2022000000,17.16,13.42,372.12
10,0700.HK,Tencent Holdings Ltd,26.17,13.29,238887000000,554552000000,235706000000,39.70,37.91,25.35
11,CSCO.OQ,Cisco Systems Inc,29.99,12.88,35753000000,56998000000,15031000000,26.84,26.87,41.28
12,SAPG.DE,SAP SE,5.82,2.75,22166000000,30871000000,4670000000,18.89,10.01,18.96
13,HPE.N,Hewlett Packard Enterprise Co,5.01,1.83,9506000000,28496000000,716000000,3.84,3.07,25.33
14,6758.T,Sony Group Corp,13.45,2.98,3140906000000,11539837000000,1203583000000,10.71,10.23,30.76
15,7974.T,Nintendo Co Ltd,22.51,17.72,885440000000,1601677000000,504013000000,30.90,37.51,27.46
16,ZTNO.PK,Zoom Technologies Inc,<NA>,<NA>,0,0,-2882050,1.97,<NA>,<NA>
17,SNOW.N,Snowflake Inc.,-15.94,-11.86,1348119000,2065659000,-880303000,<NA>,-39.50,-15.79
18,NOW.N,ServiceNow Inc,25.61,10.94,5672000000,7245000000,355000000,3.19,5.51,17.91
19,WDAY.OQ,Workday Inc,-4.93,-2.03,4500640000,6215818000,-222200000,-7.02,-4.18,3.17
20,SPLK.OQ,Splunk Inc,<NA>,-3.04,2837713000,3653708000,-235506000,-21.24,-7.27,<NA>
21,INTU.OQ,Intuit Inc,12.96,7.80,10320000000,12726000000,2571000000,24.88,19.97,22.39
22,HUBS.N,HubSpot Inc,-20.91,-8.17,1416710000,1730969000,-114964000,-6.49,-6.05,-5.37
23,MDB.OQ,MongoDB Inc,-44.00,-12.86,934736000,1284040000,-346655000,-31.74,-25.95,-43.76
24,DOCU.OQ,DocuSign Inc,-12.66,-2.44,1980917000,2515915000,-88031000,-12.61,-3.57,14.79
25,DDOG.OQ,Datadog Inc,-5.80,-2.78,1328357000,1675100000,-58695000,-3.17,-2.27,-5.79
26,ZM.OQ,Zoom Video Communications Inc,0.09,0.07,3292509000,4392960000,245429000,16.43,5.67,3.61
27,TEAM.OQ,Atlassian Corp,-99.13,-13.10,2910074000,3534647000,-345222000,-1.63,-8.80,-25.71
28,PATH.N,UiPath Inc,-12.39,-9.38,879422000,1058581000,-348283000,<NA>,-30.00,-12.21
29,CFLT.OQ,Confluent Inc,-61.35,-20.54,383529000,585944000,-462674000,<NA>,-76.16,-60.86
30,GOOGL.OQ,Alphabet Inc,23.33,16.51,156633000000,282836000000,74842000000,25.11,25.22,35.21
31,NET.N,Cloudflare Inc,-36.16,-8.84,742631000,975241000,-201203000,-27.56,-19.56,-12.75
32,PANW.OQ,Palo Alto Networks Inc,44.90,3.29,4983000000,6892700000,387300000,-1.49,8.22,63.99
33,ADSK.OQ,Autodesk Inc,106.21,9.67,4525000000,5005000000,989000000,13.42,18.90,149.43
34,ZI.OQ,ZoomInfo Technologies Inc,5.53,1.74,909800000,1098000000,215300000,<NA>,17.72,14.45
35,PLTR.N,Palantir Technologies Inc,-1.81,-1.19,1497322000,1905871000,-161201000,<NA>,-18.94,-1.35
36,DT.N,Dynatrace Inc,9.44,5.58,935639000,1158530000,98711000,0.72,7.77,10.69
37,HCP.OQ,HashiCorp Inc,-20.39,-15.76,388920000,475889000,-297287000,<NA>,-57.43,-23.01
38,SHOP.N,Shopify Inc,-25.03,-19.80,2754119000,5599864000,-822299000,-4.41,-64.70,-11.37
39,TWLO.N,Twilio Inc,-11.72,-9.85,1813577000,3826321000,-1205308000,-30.34,-32.50,-3.92
40,CRWD.OQ,CrowdStrike Holdings Inc,-11.17,-3.37,1640005000,2241236000,-190112000,-13.36,-7.13,-6.03
41,ESTC.N,Elastic NV,-58.00,-13.95,772363000,1068989000,-219172000,-24.54,-20.29,-39.70
42,GTLB.OQ,GitLab Inc,-25.68,-18.29,372656000,424336000,-193613000,<NA>,-41.90,-28.51
43,CHKP.OQ,Check Point Software Technologies Ltd,28.71,15.13,2025500000,2329900000,884300000,42.89,39.84,32.24
44,VEEV.N,Veeva Systems Inc,14.81,11.49,1545655000,2155060000,459091000,24.89,23.62,12.05
45,ZS.OQ,Zscaler Inc,-47.55,-9.41,848664000,1090946000,-327429000,-26.75,-35.16,-36.19
46,IOT.N,Samsara Inc,-25.92,-15.54,469889000,652545000,-259455000,<NA>,-37.37,-26.76
47,NVDA.OQ,NVIDIA Corp,18.86,10.69,16053000000,26974000000,4224000000,27.30,15.50,27.01
48,AKAM.OQ,Akamai Technologies Inc,11.92,6.17,2232835000,3616654000,676274000,19.07,18.19,29.05
49,DBX.OQ,Dropbox Inc,<NA>,18.38,1880700000,2324900000,181300000,-4.19,8.29,<NA>
50,RNG.N,RingCentral Inc,<NA>,-28.78,1346599000,1988330000,-648375000,-17.94,-43.96,<NA>

In [55]:
# Operating

In [62]:
fields_ef = ["TR.CommonName",
     "TR.TtlDebtToTtlEquityPct",
     "TR.NetDebtToEBITDA",
     "TR.CashandEquivalents(Period=FY0, Scale=6, curn='USD')",
     "TR.CurrentRatio",
     "TR.QuickRatio",
     "TR.InventoryTurnover",
     "TR.AcctsReceivTradeNet(Period=FY0,Scale=6, curn='USD')"]

In [63]:
df_zoom, df_zoom_peers = gt_comparison("GM", fields_ef)
df_zoom

,Company Common Name,"Total Debt to Total Equity, Percent",Net Debt To EBITDA (Daily Time Series Ratio),Cash and Equivalents,Current Ratio,Quick Ratio,Inventory Turnover,"Accounts Receivable - Trade, Net"
Instrument,,,,,,,,
GM,General Motors Co,169.19253,3.377476,19153.0,1.10176,0.93323,9.491007,13333.0
Peer Median,,111.964707,3.019401,1735.765,1.26863,0.94069,7.636845,2821.0
Peer Average,,121.906833,4.161058,8118.375196,2.00143,1.613617,8.356128,9103.501509