In [1]:
#!pip3 install textblob

In [1]:
import eikon as ek
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from textblob import TextBlob
import datetime
from datetime import time
import warnings
warnings.filterwarnings("ignore")
import configparser as cp
#https://github.com/Refinitiv-API-Samples/Article.EikonAPI.Python.NewsSentimentAnalysis

Basado en el siguiente art√≠culo:

jasonramchandani 
@rsamasiri rsamasiri Raksina Samasiri

#https://github.com/Refinitiv-API-Samples/Article.EikonAPI.Python.NewsSentimentAnalysis

In [2]:
cfg = cp.ConfigParser()
cfg.read('../refinitiv.cfg')
ek.set_app_key(cfg['eikon']['app_id'])

In [3]:
import pandas as pd
pd.merge

<function pandas.core.reshape.merge.merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | None' = None, left_on: 'IndexLabel | None' = None, right_on: 'IndexLabel | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'str | None' = None) -> 'DataFrame'>

In [4]:
from datetime import datetime, timedelta
end = datetime.today()
start = end - timedelta(days=(365.2*4))
print(start, end)

2019-10-03 20:30:56.396580 2023-10-03 15:42:56.396580

In [5]:
df = ek.get_news_headlines('R:MSFT.O AND Language:LEN', date_from=start, date_to=end, count=100)
df.head()

,versionCreated,text,storyId,sourceCode
2023-10-03 15:28:56.268,2023-10-03 15:34:13.969000+00:00,REG - Bango PLC - Total Voting Rights,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE
2023-10-03 10:26:14.160,2023-10-03 15:30:28.389000+00:00,REG - Allianz Global Invs - Top 10 Holdings,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE
2023-10-03 15:29:31.000,2023-10-03 15:29:31+00:00,"BUZZ-Amazon, Microsoft fall as UK regulator pu...",urn:newsml:newswire.refinitiv.com:20231003:nL4...,NS:RTRS
2023-10-03 14:48:08.949,2023-10-03 15:08:15.524000+00:00,REG - Haydale Graphene Ind - Result of General...,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE
2023-10-03 15:00:00.504,2023-10-03 15:00:00.504000+00:00,"ELEVATE SECURITY INTRODUCES ADAPTIVE TRUST, UN...",urn:newsml:newswire.refinitiv.com:20231003:nTU...,NS:RTRS

In [6]:
df['Polarity'] = np.nan
df['Subjectivity'] = np.nan
df['Score'] = np.nan

In [7]:
#for idx, storyId in enumerate(df['storyId'].values):  #for each row in our df dataframe
#    print(idx, storyId)
#    newsText = ek.get_news_story(storyId) #get the news story
#    print(newsText)

In [8]:
for idx, storyId in enumerate(df['storyId'].values):  #for each row in our df dataframe
    newsText = ek.get_news_story(storyId) #get the news story
    if newsText:
        soup = BeautifulSoup(newsText,"lxml") #create a BeautifulSoup object from our HTML news article
        sentA = TextBlob(soup.get_text()) #pass the text only article to TextBlob to anaylse
        df['Polarity'].iloc[idx] = sentA.sentiment.polarity #write sentiment polarity back to df
        df['Subjectivity'].iloc[idx] = sentA.sentiment.subjectivity #write sentiment subjectivity score back to df
        if sentA.sentiment.polarity >= 0.05: # attribute bucket to sentiment polartiy
            score = 'positive'
        elif  -.05 < sentA.sentiment.polarity < 0.05:
            score = 'neutral'
        else:
            score = 'negative'
        df['Score'].iloc[idx] = score #write score back to df
df.head()

,versionCreated,text,storyId,sourceCode,Polarity,Subjectivity,Score
2023-10-03 15:28:56.268,2023-10-03 15:34:13.969000+00:00,REG - Bango PLC - Total Voting Rights,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE,0.091901,0.397221,positive
2023-10-03 10:26:14.160,2023-10-03 15:30:28.389000+00:00,REG - Allianz Global Invs - Top 10 Holdings,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE,0.115646,0.342517,positive
2023-10-03 15:29:31.000,2023-10-03 15:29:31+00:00,"BUZZ-Amazon, Microsoft fall as UK regulator pu...",urn:newsml:newswire.refinitiv.com:20231003:nL4...,NS:RTRS,0.048990,0.407071,neutral
2023-10-03 14:48:08.949,2023-10-03 15:08:15.524000+00:00,REG - Haydale Graphene Ind - Result of General...,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE,0.015422,0.353602,neutral
2023-10-03 15:00:00.504,2023-10-03 15:00:00.504000+00:00,"ELEVATE SECURITY INTRODUCES ADAPTIVE TRUST, UN...",urn:newsml:newswire.refinitiv.com:20231003:nTU...,NS:RTRS,0.000000,0.000000,neutral

In [9]:
start = df['versionCreated'].min().replace(hour=0,minute=0,second=0,microsecond=0).strftime('%Y/%m/%d')
end = df['versionCreated'].max().replace(hour=0,minute=0,second=0,microsecond=0).strftime('%Y/%m/%d')
Minute = ek.get_timeseries(["MSFT.O"], start_date=start, interval="minute")
Minute

MSFT.O                 HIGH     LOW    OPEN   CLOSE  COUNT  VOLUME
Date
2023-09-29 00:00:00   314.2  313.72  314.12  313.72     48     268
2023-09-29 08:01:00  315.99  314.99  315.99   315.6     17     489
2023-09-29 08:02:00  315.56  315.35  315.56  315.35      9     120
2023-09-29 08:03:00  315.55  315.49  315.51  315.54     19     573
2023-09-29 08:04:00   315.6  315.39   315.5   315.6     18     558
...                     ...     ...     ...     ...    ...     ...
2023-10-03 22:26:00  312.85  312.84  312.85  312.84      4      20
2023-10-03 22:27:00  312.85  312.83  312.84  312.85      6     740
2023-10-03 22:28:00  312.89  312.68  312.88  312.89     40    1116
2023-10-03 22:29:00  312.87  312.87  312.87  312.87      1       3
2023-10-03 22:30:00  312.89   312.8  312.87  312.88      6      68

[2658 rows x 6 columns]

In [10]:
df['versionCreated'].min()

Timestamp('2023-09-29 16:22:57.682000+0000', tz='UTC')

In [11]:
df['twoM'] = np.nan
df['fiveM'] = np.nan
df['tenM'] = np.nan
df['thirtyM'] = np.nan
df.head(2)

,versionCreated,text,storyId,sourceCode,Polarity,Subjectivity,Score,twoM,fiveM,tenM,thirtyM
2023-10-03 15:28:56.268,2023-10-03 15:34:13.969000+00:00,REG - Bango PLC - Total Voting Rights,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE,0.091901,0.397221,positive,NaN,NaN,NaN,NaN
2023-10-03 10:26:14.160,2023-10-03 15:30:28.389000+00:00,REG - Allianz Global Invs - Top 10 Holdings,urn:newsml:newsroom.refinitiv.com:20231003:nRS...,NS:LSE,0.115646,0.342517,positive,NaN,NaN,NaN,NaN

In [12]:
df.tail()

,versionCreated,text,storyId,sourceCode,Polarity,Subjectivity,Score,twoM,fiveM,tenM,thirtyM
2023-09-29 17:18:59.014,2023-09-29 18:55:16.942000+00:00,The Schall Law Firm Encourages Investors in Ui...,urn:newsml:newsroom.refinitiv.com:20230929:nVM...,NS:CMNW,-0.087368,0.369797,negative,NaN,NaN,NaN,NaN
2023-09-29 18:30:27.000,2023-09-29 18:30:27+00:00,"What to Watch in the Week Ahead and on Monday,...",urn:newsml:newswire.refinitiv.com:20230929:nL4...,NS:RTRS,0.004158,0.376227,neutral,NaN,NaN,NaN,NaN
2023-09-29 18:03:49.000,2023-09-29 18:03:49+00:00,United States Attorney's Office for the Southe...,urn:newsml:newswire.refinitiv.com:20230929:nND...,NS:PUBT,-0.048560,0.449278,neutral,NaN,NaN,NaN,NaN
2023-09-29 16:04:57.725,2023-09-29 17:55:56.554000+00:00,Refinitiv Newscasts - Trading at Noon: Wall St...,urn:newsml:newswire.refinitiv.com:20230929:nRT...,NS:RTRS,0.079630,0.442593,positive,NaN,NaN,NaN,NaN
2023-09-29 16:22:55.323,2023-09-29 16:22:57.682000+00:00,Microsoft (MSFT) Brings 365 Copilot Capabiliti...,urn:newsml:newswire.refinitiv.com:20230929:nNR...,NS:ZACKSC,0.111827,0.543700,positive,NaN,NaN,NaN,NaN

In [13]:
for idx, newsDate in enumerate(df['versionCreated'].values):
    print(idx, newsDate)

0 2023-10-03T15:34:13.969000000
1 2023-10-03T15:30:28.389000000
2 2023-10-03T15:29:31.000000000
3 2023-10-03T15:08:15.524000000
4 2023-10-03T15:00:00.504000000
5 2023-10-03T15:00:00.301000000
6 2023-10-03T14:50:22.697000000
7 2023-10-03T14:47:48.000000000
8 2023-10-03T14:19:21.000000000
9 2023-10-03T14:00:00.000000000
10 2023-10-03T13:58:50.000000000
11 2023-10-03T13:56:16.695000000
12 2023-10-03T13:46:09.000000000
13 2023-10-03T13:43:15.323000000
14 2023-10-03T13:29:26.000000000
15 2023-10-03T13:23:38.000000000
16 2023-10-03T13:00:04.402000000
17 2023-10-03T13:00:04.221000000
18 2023-10-03T12:50:57.000000000
19 2023-10-03T11:56:21.000000000
20 2023-10-03T11:52:57.000000000
21 2023-10-03T11:08:40.000000000
22 2023-10-03T11:07:38.746000000
23 2023-10-03T11:07:02.807000000
24 2023-10-03T11:07:02.566000000
25 2023-10-03T10:36:59.000000000
26 2023-10-03T10:32:02.965000000
27 2023-10-03T10:26:13.000000000
28 2023-10-03T09:29:03.000000000
29 2023-10-03T08:20:17.890000000
30 2023-10-03T08:00:16.645000000
31 2023-10-03T07:46:09.597000000
32 2023-10-03T05:12:49.000000000
33 2023-10-03T04:46:33.000000000
34 2023-10-03T04:01:03.816000000
35 2023-10-03T04:01:03.604000000
36 2023-10-03T03:02:02.000000000
37 2023-10-03T02:57:17.762000000
38 2023-10-03T02:40:46.913000000
39 2023-10-02T22:52:46.437000000
40 2023-10-02T22:49:57.501000000
41 2023-10-02T22:49:44.474000000
42 2023-10-02T21:38:09.016000000
43 2023-10-02T21:02:41.602000000
44 2023-10-02T20:59:01.198000000
45 2023-10-02T20:32:02.060000000
46 2023-10-02T20:30:14.459000000
47 2023-10-02T19:52:14.000000000
48 2023-10-02T19:32:41.747000000
49 2023-10-02T18:34:33.000000000
50 2023-10-02T16:44:36.259000000
51 2023-10-02T16:06:33.698000000
52 2023-10-02T15:29:43.000000000
53 2023-10-02T14:56:51.000000000
54 2023-10-02T14:50:27.142000000
55 2023-10-02T14:33:45.347000000
56 2023-10-02T13:59:29.000000000
57 2023-10-02T13:01:25.000000000
58 2023-10-02T13:00:29.996000000
59 2023-10-02T13:00:13.267000000
60 2023-10-02T12:45:13.000000000
61 2023-10-02T11:11:08.000000000
62 2023-10-02T10:06:01.000000000
63 2023-10-02T07:22:06.815000000
64 2023-10-02T06:05:45.743000000
65 2023-10-02T05:16:13.090000000
66 2023-10-02T03:03:40.240000000
67 2023-10-02T02:33:16.441000000
68 2023-10-02T01:24:11.443000000
69 2023-10-02T01:03:26.314000000
70 2023-10-02T00:29:48.000000000
71 2023-10-01T22:00:43.000000000
72 2023-10-01T13:00:00.000000000
73 2023-10-01T08:45:35.000000000
74 2023-10-01T02:46:14.738000000
75 2023-10-01T02:36:06.269000000
76 2023-10-01T02:35:37.720000000
77 2023-10-01T02:35:27.956000000
78 2023-10-01T02:34:56.202000000
79 2023-09-30T07:46:18.316000000
80 2023-09-30T04:27:05.012000000
81 2023-09-30T04:21:48.741000000
82 2023-09-30T03:04:08.503000000
83 2023-09-30T02:57:31.455000000
84 2023-09-30T02:44:14.980000000
85 2023-09-30T02:43:25.236000000
86 2023-09-30T02:43:24.406000000
87 2023-09-30T02:43:02.418000000
88 2023-09-30T02:42:34.938000000
89 2023-09-30T02:40:51.061000000
90 2023-09-30T02:39:57.334000000
91 2023-09-30T02:39:53.346000000
92 2023-09-30T02:38:21.276000000
93 2023-09-29T22:18:05.000000000
94 2023-09-29T21:13:13.106000000
95 2023-09-29T18:55:16.942000000
96 2023-09-29T18:30:27.000000000
97 2023-09-29T18:03:49.000000000
98 2023-09-29T17:55:56.554000000
99 2023-09-29T16:22:57.682000000

In [20]:
idx = 0
newsDate = '2023-10-03T15:29:31.000000000'
sTime = df['versionCreated'][idx]
sTime = sTime.replace(second=0,microsecond=0)
sTime

Timestamp('2023-10-03 15:34:00+0000', tz='UTC')

In [21]:
t0 = Minute.iloc[Minute.index.get_loc(sTime),2]
t0

KeyError: Timestamp('2023-10-03 15:34:00+0000', tz='UTC')

In [62]:
Minute.iloc[Minute.index.get_loc((sTime + timedelta(minutes=2))),3]

283.2

In [17]:
for idx, newsDate in enumerate(df['versionCreated'].values):
    sTime = df['versionCreated'][idx]
    sTime = sTime.replace(second=0,microsecond=0)
    try:
        t0 = Minute.iloc[Minute.index.get_loc(sTime),2]
        df['twoM'][idx] = ((Minute.iloc[Minute.index.get_loc((sTime + timedelta(minutes=2))),3]/(t0)-1)*100)
        df['fiveM'][idx] = ((Minute.iloc[Minute.index.get_loc((sTime + timedelta(minutes=5))),3]/(t0)-1)*100)
        df['tenM'][idx] = ((Minute.iloc[Minute.index.get_loc((sTime + timedelta(minutes=10))),3]/(t0)-1)*100) 
        df['thirtyM'][idx] = ((Minute.iloc[Minute.index.get_loc((sTime + timedelta(minutes=30))),3]/(t0)-1)*100)
    except:
        pass
df.head()

,versionCreated,text,storyId,sourceCode,Polarity,Subjectivity,Score,twoM,fiveM,tenM,thirtyM
2023-04-18 07:46:19.000,2023-04-18 17:52:46+00:00,"U.S. RESEARCH ROUNDUP-Aterian, Berkshire Hatha...",urn:newsml:newswire.refinitiv.com:20230418:nL4...,NS:RTRS,0.026779,0.066479,neutral,-0.030055,-0.098416,-0.193609,-0.124624
2023-04-18 17:44:05.666,2023-04-18 17:44:05.666000+00:00,Microsoft (MSFT) Azure Expands Strategic Partn...,urn:newsml:newswire.refinitiv.com:20230418:nNR...,NS:ZACKSC,0.116939,0.479778,positive,0.044555,0.117982,0.070026,-0.076792
2023-04-18 17:30:54.000,2023-04-18 17:30:54+00:00,LIVE MARKETS-Search and disrupt,urn:newsml:newswire.refinitiv.com:20230418:nL1...,NS:RTRS,0.026409,0.371817,neutral,-0.052845,0.023541,0.048609,-0.053818
2023-04-18 17:25:09.000,2023-04-18 17:25:09+00:00,UN Women - Overcoming gender-based violence as...,urn:newsml:newswire.refinitiv.com:20230418:nND...,NS:PUBT,0.117577,0.310451,positive,-0.027758,-0.089969,-0.045869,0.064189
2023-04-18 17:22:03.000,2023-04-18 17:22:03+00:00,US FTC leaders will target AI that violates ci...,urn:newsml:newswire.refinitiv.com:20230418:nL1...,NS:RTRS,-0.077982,0.649912,negative,0.072639,0.045139,-0.049375,0.142361

In [64]:
grouped = df.groupby(['Score']).mean()
grouped

          Polarity  Subjectivity      twoM     fiveM      tenM   thirtyM
Score
negative -0.074614      0.318861 -0.042092 -0.040307 -0.066435  0.073719
neutral   0.003039      0.242634  0.018427  0.048040  0.042721 -0.026442
positive  0.140777      0.441769  0.013360  0.006920  0.016765 -0.018865